device : "cpu"
latent_factors : 1000
epochs: 20
lr : 0.002
batch_size : 512
weight_decay: 0.00001
top_k : 50
margin: 3
num_candidate_neg_samples : 20
num_hard_neg_samples  : 3
num_random_neg_samples : 3